package client

// GitHubWebhookEvents maps each GitHub webhook event type to its known action
// values. Events with an empty slice have no action field. This reference is
// provided for users configuring global-ignore-pre / global-ignore-post
// patterns; it is NOT used for runtime validation since GitHub may add new
// events or actions at any time.
//
// Source: https://docs.github.com/en/webhooks/webhook-events-and-payloads
var GitHubWebhookEvents = map[string][]string{
	"branch_protection_configuration": {"disabled", "enabled"},
	"branch_protection_rule":          {"created", "deleted", "edited"},
	"check_run":                       {"completed", "created", "requested_action", "rerequested"},
	"check_suite":                     {"completed", "requested", "rerequested"},
	"code_scanning_alert":             {"appeared_in_branch", "closed_by_user", "created", "fixed", "reopened", "reopened_by_user"},
	"commit_comment":                  {"created"},
	"create":                          {}, // branch or tag created
	"custom_property":                 {"created", "deleted", "updated"},
	"custom_property_values":          {"updated"},
	"delete":                          {}, // branch or tag deleted
	"dependabot_alert":                {"auto_dismissed", "auto_reopened", "created", "dismissed", "fixed", "reintroduced", "reopened"},
	"deploy_key":                      {"created", "deleted"},
	"deployment":                      {"created"},
	"deployment_protection_rule":      {"requested"},
	"deployment_review":               {"approved", "rejected", "requested"},
	"deployment_status":               {"created"},
	"discussion":                      {"answered", "category_changed", "created", "deleted", "edited", "labeled", "locked", "pinned", "transferred", "unanswered", "unlabeled", "unlocked", "unpinned"},
	"discussion_comment":              {"created", "deleted", "edited"},
	"fork":                            {},
	"github_app_authorization":        {"revoked"},
	"gollum":                          {}, // wiki page events
	"installation":                    {"created", "deleted", "new_permissions_accepted", "suspend", "unsuspend"},
	"installation_repositories":       {"added", "removed"},
	"installation_target":             {"renamed"},
	"issue_comment":                   {"created", "deleted", "edited"},
	"issues":                          {"assigned", "closed", "deleted", "demilestoned", "edited", "labeled", "locked", "milestoned", "opened", "pinned", "reopened", "transferred", "unassigned", "unlabeled", "unlocked", "unpinned"},
	"label":                           {"created", "deleted", "edited"},
	"marketplace_purchase":            {"cancelled", "changed", "pending_change", "pending_change_cancelled", "purchased"},
	"member":                          {"added", "edited", "removed"},
	"membership":                      {"added", "removed"},
	"merge_group":                     {"checks_requested", "destroyed"},
	"meta":                            {"deleted"},
	"milestone":                       {"closed", "created", "deleted", "edited", "opened"},
	"org_block":                       {"blocked", "unblocked"},
	"organization":                    {"deleted", "member_added", "member_invited", "member_removed", "renamed"},
	"package":                         {"published", "updated"},
	"page_build":                      {},
	"personal_access_token_request":   {"approved", "cancelled", "created", "denied"},
	"ping":                            {},
	"project":                         {"closed", "created", "deleted", "edited", "reopened"},
	"project_card":                    {"converted", "created", "deleted", "edited", "moved"},
	"project_column":                  {"created", "deleted", "edited", "moved"},
	"projects_v2":                     {"closed", "created", "deleted", "edited", "reopened"},
	"projects_v2_item":                {"archived", "converted", "created", "deleted", "edited", "reordered", "restored"},
	"projects_v2_status_update":       {"created", "deleted", "edited"},
	"public":                          {},
	"pull_request":                    {"assigned", "auto_merge_disabled", "auto_merge_enabled", "closed", "converted_to_draft", "demilestoned", "dequeued", "edited", "enqueued", "labeled", "locked", "milestoned", "opened", "ready_for_review", "reopened", "review_request_removed", "review_requested", "synchronize", "unassigned", "unlabeled", "unlocked"},
	"pull_request_review":             {"dismissed", "edited", "submitted"},
	"pull_request_review_comment":     {"created", "deleted", "edited"},
	"pull_request_review_thread":      {"resolved", "unresolved"},
	"push":                            {},
	"registry_package":                {"published", "updated"},
	"release":                         {"created", "deleted", "edited", "prereleased", "published", "released", "unpublished"},
	"repository":                      {"archived", "created", "deleted", "edited", "privatized", "publicized", "renamed", "transferred", "unarchived"},
	"repository_advisory":             {"published", "reported"},
	"repository_dispatch":             {}, // custom event_type in payload
	"repository_import":               {},
	"repository_ruleset":              {"created", "deleted", "edited"},
	"repository_vulnerability_alert":  {"create", "dismiss", "resolve"},
	"secret_scanning_alert":           {"created", "resolved", "reopened", "validated"},
	"secret_scanning_alert_location":  {"created"},
	"security_advisory":               {"performed", "published", "updated", "withdrawn"},
	"security_and_analysis":           {},
	"sponsorship":                     {"cancelled", "created", "edited", "pending_cancellation", "pending_tier_change", "tier_changed"},
	"star":                            {"created", "deleted"},
	"status":                          {},
	"sub_issues":                      {"parent_issue_added", "parent_issue_removed", "sub_issue_added", "sub_issue_removed"},
	"team":                            {"added_to_repository", "created", "deleted", "edited", "removed_from_repository"},
	"team_add":                        {},
	"watch":                           {"started"},
	"workflow_dispatch":               {},
	"workflow_job":                     {"completed", "in_progress", "queued", "waiting"},
	"workflow_run":                     {"completed", "in_progress", "requested"},
}
